In [2]:
# Dependencies
from pathlib import Path
from sqlalchemy import create_engine, text

import pandas as pd
import json

In [3]:
# NOTE: that due to the size of the data, these SQLite tables have been significantly reduced only to show the SQLite pathway and SQLAlchemy pull.
# We host our cleaned CSV files on our local drives in order to use and continue our analysis.

# Create a reference to the database 
database_path = Path("Resources/ny_airbnb.db")

# Create Engine
engine = create_engine(f"sqlite:///{database_path}")

In [4]:
# Select all data from the three New York AirBnb tables 
query_ny_reviews = text("SELECT * FROM merged;")
sample_ny_review_data = engine.execute(query_ny_reviews)

sample_ny_review_df = pd.DataFrame(sample_ny_review_data)
sample_ny_review_df.head()

,listing_id,listing_url,name,host_id,host_url,host_name,host_since,host_is_superhost,host_listings_count,host_total_listings_count,...,number_of_reviews_l30d,first_review,last_review,review_scores_rating,calculated_host_listings_count,reviews_per_month,date,available,price,adjusted_price
0,2595,https://www.airbnb.com/rooms/2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,f,7.0,9.0,...,0,2009-11-21,2022-06-21,4.68,3,0.3,2023-07-31,f,$240.00,$240.00
1,2595,https://www.airbnb.com/rooms/2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,f,7.0,9.0,...,0,2009-11-21,2022-06-21,4.68,3,0.3,2023-08-01,f,$240.00,$240.00
2,2595,https://www.airbnb.com/rooms/2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,f,7.0,9.0,...,0,2009-11-21,2022-06-21,4.68,3,0.3,2023-08-02,f,$240.00,$240.00
3,2595,https://www.airbnb.com/rooms/2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,f,7.0,9.0,...,0,2009-11-21,2022-06-21,4.68,3,0.3,2023-08-03,t,$240.00,$240.00
4,2595,https://www.airbnb.com/rooms/2595,Rental unit in New York · ★4.68 · Studio · 1 b...,2845,https://www.airbnb.com/users/show/2845,Jennifer,2008-09-09,f,7.0,9.0,...,0,2009-11-21,2022-06-21,4.68,3,0.3,2023-08-04,t,$240.00,$240.00

In [5]:
json_sample_ny_review_df = json.dumps(sample_ny_review_df.to_dict(orient='records'), indent=2)

with open('Resources/data.js','w') as file:
    file.write(f'nydata = {json_sample_ny_review_df};')

print("DataFrame saved as json_sample_ny_review.js")

DataFrame saved as json_sample_ny_review.js

In [6]:
reviews = 'Resources/cleaned_reviews_ny.csv'
reviews_df = pd.read_csv(reviews, encoding="ISO-8859-1")
reviews_df.head()

   listing_id     id        date  reviewer_id reviewer_name
0        2595  17857  2009-11-21        50679          Jean
1        2595  19176  2009-12-05        53267          Cate
2        2595  19760  2009-12-10        38960         Anita
3        2595  34320  2010-04-09        71130       Kai-Uwe
4        2595  46312  2010-05-25       117113        Alicia

In [7]:
ny_review_df = json.dumps(reviews_df.to_dict(orient='records'), indent=2)

with open('Resources/review_data.js','w') as file:
    file.write(f'reviews = {ny_review_df};')

print("DataFrame saved as ny_review.js")

DataFrame saved as ny_review.js